name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

        - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip libffi-dev libssl-dev \
          autoconf automake build-essential libtool pkg-config \
          zlib1g-dev openjdk-11-jdk python3-venv

        # Install Android SDK Build Tools with AIDL
        mkdir -p $HOME/android-sdk/cmdline-tools
        cd $HOME/android-sdk/cmdline-tools
        curl -O https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
        unzip commandlinetools-linux-*.zip -d tools
        yes | tools/bin/sdkmanager --sdk_root=$HOME/android-sdk \
          "platform-tools" "platforms;android-31" "build-tools;31.0.0"
        export PATH=$HOME/android-sdk/platform-tools:$HOME/android-sdk/build-tools/31.0.0:$PATH


    - name: Install Buildozer
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install cython
        pip install buildozer

    - name: Build the APK
      run: |
        source venv/bin/activate
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: crypto-search-apk
        path: bin/*.apk
